[package]
name = "with-cc-build"
version = "1.0.0"
edition = "2021"
publish = false # "private"

[[bin]]
name = "example"
path = "src/main.rs"

[dependencies]
tar.workspace = true
zstd.workspace = true
