[workspace]
resolver = "2"
members = [
    "with-cc-build"
]

[workspace.dependencies]
zstd = "0.13"
tar = "0.4.38"

[patch.crates-io]
cc = { git = "https://github.com/ArchangelX360/cc-rs", rev = "fb0318ba4567c95cdf280399c57f3b09ebdcb45f" }
